package com.rabidgremlin.romo.cmdgen;

/**
 * Interface that needs to be implemented by a Step in a sequence of Romo commands.
 * 
 * @author jack@rabidgremlin.com
 * 
 */
public interface SequenceStep
{
  /**
   * This method returns the length of the step in frames/samples.
   * 
   * @return The number of frames/samples this step will generate.
   */
  int getLengthInFrames();

  /**
   * This method returns the data generated by the step. First dimension is the channels, 0 = left channel, 1 = right channel.
   * 
   * Second dimension should be getLengthInFrames() big and should contain values of -1 to 1.
   * 
   * @return The data generated by the step.
   */
  double[][] getData();
}
